#! /usr/bin/env perl -w
#-*- mode: Perl -*-

use lib 'lib';

use strict;
use warnings;

use Log::Any::Adapter;

Log::Any::Adapter->set('Stderr', log_level => 'info' );

use App::JIRAPrint;

my $j = App::JIRAPrint->new();

# Force config loading
$j->config();

binmode STDOUT, 'utf8';
print $j->process_template();
